jobs:
 - name: daily_table_refresh
   targetName: dev 
   schedule: 0 12 * * * 
   retryOnFailure: true
   steps:
     - name: run models 
       command: dbt run
     - name: test models
       command: dbt test

# dbt run --models stg_tpch_line_items.sql stg_tpch_orders.sql